apiVersion: apps/v1
kind: Deployment
mietadata:
  name: erick-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erick-api
  template:
    metadata:
      labels:
        app: erick-api
    spec:
      containers:
        - name: erick-api
          image: us-docker.pkg.dev/cit-262-417504/erick-api/api-tests
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10